name: Check Changes

on:
#  schedule:
#    # 01:00 UTC each day
#    - cron:  '0 1 * * *'
    
  workflow_dispatch:
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Docker target meta
        id: fetch_tags
        uses: mxpicture/action-docker-hub-fetch-tags@v1.0.2
        with:
          repository: mxpicture/openwrt-rootfs

      - run: echo ${{ steps.fetch_tags.outputs.count }}

      - name: Get tags, compare docker hub image dates and trigger deploy
        uses: actions/github-script@v5
        with:
          script: |
            const tags = (await github.request("https://api.github.com/repos/" 
              + context.repo.owner + "/" + context.repo.repo + "/tags")).data

            const target_tags = ${{ steps.fetch_tags.outputs.results }}
            console.log(target_tags)
            
            for (const tag of tags) {
              console.log(tag.name)

            }
