name: Check Changes

on:
#  schedule:
#    # 01:00 UTC each day
#    - cron:  '0 1 * * *'
    
  workflow_dispatch:
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Docker target meta
        id: target_meta
        uses: David-Lor/action-dockerhub-get-tag-metadata@0.1.1
        with:
          image: mxpicture/openwrt-rootfs

      - run: |
          echo "${{ steps.target_meta.outputs }}"

      - name: Get tags, compare docker hub image dates and trigger deploy
        uses: actions/github-script@v5
        with:
          script: |
            const tags = (await github.request("https://api.github.com/repos/" 
              + context.repo.owner + "/" + context.repo.repo + "/tags")).data


            console.log(${{ steps.meta.outputs }})
            for (const tag of tags) {
              console.log(tag.name)

            }
