name: Check Changes

on:
#  schedule:
#    # 01:00 UTC each day
#    - cron:  '0 1 * * *'
    
  workflow_dispatch:
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v5
        with:
          script: |
            const opts = github.rest.repos.listTags(context.repo)

            const branches = await github.paginate(opts)
            
            for (const branch of branches) {
              console.log(branch.name)
            }
