name: Check Changes

on:
#  schedule:
#    # 01:00 UTC each day
#    - cron:  '0 1 * * *'
    
  workflow_dispatch:
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: mxpicture/openwrt-rootfs

      - run: |
          echo "${{ steps.meta.outputs }}"

      - name: Get tags, compare docker hub image dates and trigger deploy
        uses: actions/github-script@v5
        with:
          script: |
            const tags = (await github.request("https://api.github.com/repos/" 
              + context.repo.owner + "/" + context.repo.repo + "/tags")).data


            console.log(${{ steps.meta.outputs }})
            for (const tag of tags) {
              console.log(tag.name)

            }
