name: Check Changes

on:
#  schedule:
#    # 01:00 UTC each day
#    - cron:  '0 1 * * *'
    
  workflow_dispatch:
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Get branches & Dispatch events in order to deploy docker images
        uses: actions/github-script@v5
        with:
          script: |
            const branches = github.rest.branches()
            echo branches
            
