name: Check Changes

on:
#  schedule:
#    # 01:00 UTC each day
#    - cron:  '0 1 * * *'
    
  workflow_dispatch:
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: mxpicture
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker target get tags
        id: target_tags
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://registry.hub.docker.com/v2/repositories/mxpicture/openwrt-rootfs/tags"
          customHeaders: '{ "Accept": "application/json", "Content-Type": "application/json" }'

      - run: |
          echo "${{ steps.target_tags.outputs }}"

      - name: Get tags, compare docker hub image dates and trigger deploy
        uses: actions/github-script@v5
        with:
          script: |
            const tags = (await github.request("https://api.github.com/repos/" 
              + context.repo.owner + "/" + context.repo.repo + "/tags")).data


            console.log(${{ steps.meta.outputs }})
            for (const tag of tags) {
              console.log(tag.name)

            }
