name: Check Changes

on:
#  schedule:
#    # 01:00 UTC each day
#    - cron:  '0 1 * * *'
  
#  push:

  workflow_dispatch:
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Docker target tags
        id: fetch_target_tags
        uses: mxpicture/action-docker-hub-fetch-tags@v1.0.3
        with:
          repository: mxpicture/openwrt-rootfs
          max_items: "999999"

      - name: Docker source tags
        id: fetch_source_tags
        uses: mxpicture/action-docker-hub-fetch-tags@v1.0.3
        with:
          repository: openwrtorg/rootfs
          max_items: "999999"

      - name: Get tags, compare docker hub image dates and trigger deploy
        uses: actions/github-script@v5
        with:
          script: |
            const tags = (await github.request("https://api.github.com/repos/" 
              + context.repo.owner + "/" + context.repo.repo + "/tags")).data

            const target_tags = ${{ steps.fetch_target_tags.outputs.results }}
            const source_tags = ${{ steps.fetch_source_tags.outputs.results }}

            for (const tag of tags) {
              console.log("Processing tag: " + tag.name)

              for (const target_tag of target_tags) {
                if ( target_tag.name === tag.name ) {
                  for (const source_tag of source_tags) {
                    if ( source_tag.name === target_tag.name && source_tag.last_updated > target_tag.last_updated ) {
                      console.log("Trigger event for tag: " + tag.name)

                      await github.rest.repos.createDispatchEvent({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        event_type: "docker_hub",
                        client_payload: {
                          tag: tag.name
                        }
                      })
                    }
                  }  
                }
              }
            }
