name: Force deploy all

on:
  workflow_dispatch:
  
jobs:
  get_tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.get.outputs.result }}
    steps:
      - name: Get tags
        uses: actions/github-script@v5
        id: get
        with:
          script: |
            const tags = (await github.request("https://api.github.com/repos/" 
              + context.repo.owner + "/" + context.repo.repo + "/tags")).data
            
            let output = []
            
            for(let i=0; i<tags.length; i++) {
              output.push({ "name": tags[i].name })
            }

            return output

      - name: Generate Matrix
        id: generate_matrix
        run: |
          TAGS='${{ toJSON(steps.get.outputs.result) }}'
          echo ::set-output name=tags::${TAGS}

  echo_matrix:
    runs-on: ubuntu-latest
    needs:
      - get_tags
    steps:
      - name: Echo previous outputs
        run: echo "${{ toJSON(needs.get_tags.outputs) }}"
  
  dispatch:
    needs: 
      - get_tags
      - echo_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        tag: ${{ fromJSON(needs.get_tags.outputs.tags) }}
    steps:
      - name: Dispatch deploy
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: docker_hub
          client-payload: '{"tag": "${{ matrix.tag }}"}'
